table _Medidas
	lineageTag: 13027f4a-71f7-4312-a3ed-ea5aa122dbdf

	measure 'Faturamento Total' = SUM(Vendas[ValorVenda])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: KPIs Principais
		lineageTag: f2abe05c-1703-40af-8f1b-adfec27878b9

	measure 'Volume de Vendas' = COUNTROWS(Vendas)
		formatString: 0
		displayFolder: KPIs Principais
		lineageTag: 077ff998-bddb-4caa-a3ca-4acaa9a8b462

	measure 'Ticket Medio' = DIVIDE([Faturamento Total], [Volume de Vendas],0)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: KPIs Principais
		lineageTag: 674d91a4-ca94-4d7a-84a6-d2f13023e1c2

	measure 'Custo Total' = SUM(Vendas[Custo])
		formatString: 0
		displayFolder: KPIs Principais
		lineageTag: 61e9d114-0b89-4080-baa0-5c37bcb91455

	measure 'Total Comissão' = SUM(Vendas[Valor Comissão ])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: KPIs Principais
		lineageTag: 7ac49da6-4373-4c9e-8bf1-0e9d76c63fbe

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Lucro Líquido' = [Faturamento Total] - [Custo Total] - [Total Comissão]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: KPIs Principais
		lineageTag: eb508509-55b6-4c39-8a3a-7f707029c78b

	measure 'Margem de Lucro %' = DIVIDE([Lucro Líquido], [Faturamento Total],0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Variações e Percentuais
		lineageTag: d42dfb6d-b2e9-4c80-96f6-a9f310609b5e

	measure 'Card HTML Faturamento' =
			
			VAR Valor = FORMAT([Faturamento Total], "R$ #,##0.00")
			VAR Perc = [Var % Faturamento]
			
			VAR Indicador =
			IF(
			    ISBLANK(Perc),
			    "",
			    IF(
			        Perc >= 0,
			        "<div style='
			            color:#6EEB83;
			            font-size:12px;
			            font-weight:600;
			            margin-top:4px;
			            white-space:nowrap;
			        '>
			        ▲ " & FORMAT(Perc,"0.0%") & "
			        </div>",
			
			        "<div style='
			            color:#FF8A80;
			            font-size:12px;
			            font-weight:600;
			            margin-top:4px;
			            white-space:nowrap;
			        '>
			        ▼ " & FORMAT(ABS(Perc),"0.0%") & "
			        </div>"
			    )
			)
			
			RETURN
			"
			<div style='
			    width:100%;
			    height:100%;
			    border-radius:14px;
			    padding:14px 18px;
			    box-sizing:border-box;
			    background:linear-gradient(135deg, #2708A0 0%, #058ED9 100%);
			    font-family:Segoe UI, sans-serif;
			    position:relative;
			    overflow:hidden;
			    box-shadow: 0 6px 12px rgba(0,0,0,0.08);
			'>
			
			    <div style='
			        position:absolute;
			        top:-30px;
			        right:-20px;
			        width:90px;
			        height:90px;
			        border-radius:50%;
			        background:rgba(255,255,255,.1);
			    '></div>
			
			    <div style='
			        display:flex;
			        align-items:center;
			        justify-content:space-between;
			        height:100%;
			        position:relative;
			        z-index:1;
			    '>
			
			        <div>
			            <div style='
			                font-size:13px;
			                color:#EBEBEB;
			                margin-bottom:4px;
			            '>
			                Faturamento Total
			            </div>
			
			            <div style='
			                font-size:26px;
			                font-weight:700;
			                color:#FFFFFF;
			                line-height:28px;
			            '>
			                " & Valor & "
			            </div>
			
			            " & Indicador & "
			        </div>
			
			        <div style='
			            display:flex;
			            align-items:center;
			            justify-content:center;
			            width:44px;
			            height:44px;
			            border-radius:50%;
			            background-color:#FFFFFF;
			            box-shadow:0 4px 8px rgba(0,0,0,.15);
			        '>
			            <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='#2708A0' width='28px' height='28px'>
			                <path d='M11.8 10.9c-2.27-.59-3-1.2-3-2.15 0-1.09 1.01-1.85 2.7-1.85 1.78 0 2.44.85 2.5 2.1h2.21c-.07-1.72-1.12-3.3-3.21-3.81V3h-3v2.16c-1.94.42-3.5 1.68-3.5 3.61 0 2.31 1.91 3.46 4.7 4.13 2.5.6 3 1.48 3 2.41 0 .69-.49 1.79-2.7 1.79-2.06 0-2.87-.92-2.98-2.1h-2.2c.12 2.19 1.76 3.42 3.68 3.83V21h3v-2.15c1.95-.37 3.5-1.5 3.5-3.55 0-2.84-2.43-3.81-4.7-4.4z'/>
			            </svg>
			        </div>
			
			    </div>
			
			</div>
			"
		displayFolder: UI e Design
		lineageTag: b81e93d1-e85c-4859-ae38-3cbdeb262217

	measure 'Card HTML Volume Vendas' =
			
			VAR Valor = FORMAT([Volume de Vendas], "#,##0")
			VAR Perc = [Var % Volume]
			
			VAR Indicador =
			IF(
			    ISBLANK(Perc),
			    "",
			    IF(
			        Perc >= 0,
			        "<div style='
			            color:#6EEB83;
			            font-size:12px;
			            font-weight:600;
			            margin-top:4px;
			            white-space:nowrap;
			        '>
			        ▲ " & FORMAT(Perc,"0.0%") & "
			        </div>",
			
			        "<div style='
			            color:#FF8A80;
			            font-size:12px;
			            font-weight:600;
			            margin-top:4px;
			            white-space:nowrap;
			        '>
			        ▼ " & FORMAT(ABS(Perc),"0.0%") & "
			        </div>"
			    )
			)
			
			RETURN
			"
			<div style='
			    width:100%;
			    height:100%;
			    border-radius:14px;
			    padding:14px 18px;
			    box-sizing:border-box;
			    background:linear-gradient(135deg, #058ED9 0%, #2708A0 100%);
			    font-family:Segoe UI, sans-serif;
			    position:relative;
			    overflow:hidden;
			    box-shadow: 0 6px 12px rgba(0,0,0,0.08);
			'>
			
			    <div style='
			        position:absolute;
			        top:-30px;
			        right:-20px;
			        width:90px;
			        height:90px;
			        border-radius:50%;
			        background:rgba(255,255,255,.1);
			    '></div>
			
			    <div style='
			        display:flex;
			        align-items:center;
			        justify-content:space-between;
			        height:100%;
			        position:relative;
			        z-index:1;
			    '>
			
			        <div>
			            <div style='
			                font-size:13px;
			                color:#EBEBEB;
			                margin-bottom:4px;
			            '>
			                Volume de Vendas
			            </div>
			
			            <div style='
			                font-size:26px;
			                font-weight:700;
			                color:#FFFFFF;
			                line-height:28px;
			            '>
			                " & Valor & "
			            </div>
			
			            " & Indicador & "
			        </div>
			
			        <div style='
			            display:flex;
			            align-items:center;
			            justify-content:center;
			            width:44px;
			            height:44px;
			            border-radius:50%;
			            background-color:#FFFFFF;
			            box-shadow: 0 4px 8px rgba(0,0,0,0.15);
			        '>
			            <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='#058ED9' width='28px' height='28px'>
			                <path d='M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z'/>
			            </svg>
			        </div>
			
			    </div>
			
			</div>
			"
		displayFolder: UI e Design
		lineageTag: 50dd292a-ec4e-4570-ba9e-c1fb3397a9aa

	measure 'Card HTML Ticket Medio' =
			
			VAR Valor = FORMAT([Ticket Medio], "R$ #,##0.00")
			
			VAR Perc = [Var % Ticket]
			
			-- Indicador PADRONIZADO para não alterar o tamanho do cartão
			VAR Indicador =
			IF(
			    ISBLANK(Perc),
			    "",
			    IF(
			        Perc >= 0,
			        "<div style='
			            color:#6EEB83;
			            font-size:12px;
			            font-weight:600;
			            margin-top:4px;
			            white-space:nowrap;
			        '>
			        ▲ " & FORMAT(Perc,"0.0%") & "
			        </div>",
			
			        "<div style='
			            color:#FF8A80;
			            font-size:12px;
			            font-weight:600;
			            margin-top:4px;
			            white-space:nowrap;
			        '>
			        ▼ " & FORMAT(ABS(Perc),"0.0%") & "
			        </div>"
			    )
			)
			
			RETURN
			"
			<div style='
			    width:100%;
			    height:100%;
			    border-radius:14px;
			    padding:14px 18px;
			    box-sizing:border-box;
			    background:linear-gradient(135deg, #2708A0 0%, #058ED9 100%);
			    font-family:Segoe UI, sans-serif;
			    position:relative;
			    overflow:hidden;
			    box-shadow: 0 6px 12px rgba(0,0,0,0.08);
			'>
			
			    <div style='
			        position:absolute;
			        top:-30px;
			        right:-20px;
			        width:90px;
			        height:90px;
			        border-radius:50%;
			        background:rgba(255,255,255,.1);
			    '></div>
			
			    <div style='
			        display:flex;
			        align-items:center;
			        justify-content:space-between;
			        height:100%;
			        position:relative;
			        z-index:1;
			    '>
			
			        <div>
			            <div style='
			                font-size:13px;
			                color:#EBEBEB;
			                margin-bottom:4px;
			            '>
			                Ticket Médio
			            </div>
			
			            <div style='
			                font-size:26px;
			                font-weight:700;
			                color:#FFFFFF;
			                line-height:28px;
			            '>
			                " & Valor & "
			            </div>
			
			            " & Indicador & "
			        </div>
			
			        <div style='
			            display:flex;
			            align-items:center;
			            justify-content:center;
			            width:44px;
			            height:44px;
			            border-radius:50%;
			            background-color:#FFFFFF;
			            box-shadow: 0 4px 8px rgba(0,0,0,0.15);
			        '>
			            <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='#2708A0' width='28px' height='28px'>
			                <path d='M21.41 11.58l-9-9C12.05 2.22 11.55 2 11 2H4c-1.1 0-2 .9-2 2v7c0 .55.22 1.05.59 1.42l9 9c.36.36.86.58 1.41.58.55 0 1.05-.22 1.41-.59l7-7c.37-.36.59-.86.59-1.41 0-.55-.23-1.06-.59-1.42zM5.5 7C4.67 7 4 6.33 4 5.5S4.67 4 5.5 4 7 4.67 7 5.5 6.33 7 5.5 7z'/>
			            </svg>
			        </div>
			
			    </div>
			
			</div>
			"
		displayFolder: UI e Design
		lineageTag: d9154875-4888-47ad-9e44-57a0ea3ed35c

	measure 'Card HTML Lucro Liquido' =
			
			VAR Valor = FORMAT([Lucro Líquido], "R$ #,##0.00")
			VAR Perc = [Var % Lucro]
			
			VAR Indicador =
			IF(
			    ISBLANK(Perc),
			    "",
			    IF(
			        Perc >= 0,
			        "<div style='
			            color:#6EEB83;
			            font-size:12px;
			            font-weight:600;
			            margin-top:4px;
			            white-space:nowrap;
			        '>
			        ▲ " & FORMAT(Perc,"0.0%") & "
			        </div>",
			
			        "<div style='
			            color:#FF8A80;
			            font-size:12px;
			            font-weight:600;
			            margin-top:4px;
			            white-space:nowrap;
			        '>
			        ▼ " & FORMAT(ABS(Perc),"0.0%") & "
			        </div>"
			    )
			)
			
			RETURN
			"
			<div style='
			    width:100%;
			    height:100%;
			    border-radius:14px;
			    padding:14px 18px;
			    box-sizing:border-box;
			    background:linear-gradient(135deg, #058ED9 0%, #2708A0 100%);
			    font-family:Segoe UI, sans-serif;
			    position:relative;
			    overflow:hidden;
			    box-shadow: 0 6px 12px rgba(0,0,0,0.08);
			'>
			
			    <div style='
			        position:absolute;
			        top:-30px;
			        right:-20px;
			        width:90px;
			        height:90px;
			        border-radius:50%;
			        background:rgba(255,255,255,.1);
			    '></div>
			
			    <div style='
			        display:flex;
			        align-items:center;
			        justify-content:space-between;
			        height:100%;
			        position:relative;
			        z-index:1;
			    '>
			
			        <div>
			            <div style='
			                font-size:13px;
			                color:#EBEBEB;
			                margin-bottom:4px;
			            '>
			                Lucro Líquido
			            </div>
			
			            <div style='
			                font-size:26px;
			                font-weight:700;
			                color:#FFFFFF;
			                line-height:28px;
			            '>
			                " & Valor & "
			            </div>
			
			            " & Indicador & "
			        </div>
			
			        <div style='
			            display:flex;
			            align-items:center;
			            justify-content:center;
			            width:44px;
			            height:44px;
			            border-radius:50%;
			            background-color:#FFFFFF;
			            box-shadow: 0 4px 8px rgba(0,0,0,0.15);
			        '>
			            <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='#058ED9' width='28px' height='28px'>
			                <path d='M16 6l2.29 2.29-4.88 4.88-4-4L2 16.59 3.41 18l6-6 4 4 6.3-6.29L22 12V6z'/>
			            </svg>
			        </div>
			
			    </div>
			
			</div>
			"
		displayFolder: UI e Design
		lineageTag: ff805e1c-49dc-4bc5-8d2e-f89e5eb3bc2a

	measure 'Faturamento Mês Anterior' =
			
			CALCULATE(
			    [Faturamento Total],
			    DATEADD(dCalendario[Date], -1, MONTH)
			)
		displayFolder: Inteligência de Tempo
		lineageTag: eb527a79-4707-43cc-b43d-1c8333aaabc3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lucro Mês Anterior' =
			
			CALCULATE(
			    [Lucro Líquido],
			    DATEADD(dCalendario[Date], -1, MONTH)
			)
		displayFolder: Inteligência de Tempo
		lineageTag: fc299665-ad9f-420b-b2f6-faab372cd58a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Volume Mês Anterior' =
			
			CALCULATE(
			    [Volume de Vendas],
			    DATEADD(dCalendario[Date], -1, MONTH)
			)
		formatString: 0
		displayFolder: Inteligência de Tempo
		lineageTag: 87aa580c-6061-4b94-b182-50e142f83004

	measure 'Ticket Médio Mês Anterior' =
			
			CALCULATE(
			    [Ticket Medio],
			    DATEADD(dCalendario[Date], -1, MONTH)
			)
		displayFolder: Inteligência de Tempo
		lineageTag: b19f05de-3078-429c-a0e0-cad6c2436487

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var % Faturamento' =
			
			DIVIDE(
			    [Faturamento Total] - [Faturamento Mês Anterior],
			    [Faturamento Mês Anterior]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Variações e Percentuais
		lineageTag: 8dcfda81-311f-4060-ab59-e318f3fa8102

	measure 'Var % Lucro' =
			
			DIVIDE(
			    [Lucro Líquido] - [Lucro Mês Anterior],
			    [Lucro Mês Anterior]
			)
		displayFolder: Variações e Percentuais
		lineageTag: d2034f16-3679-421a-9752-d426c4544c5d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var % Volume' =
			
			DIVIDE(
			    [Volume de Vendas] - [Volume Mês Anterior],
			    [Volume Mês Anterior]
			)
		displayFolder: Variações e Percentuais
		lineageTag: 19f75322-7748-479e-a064-2bbeee1b1256

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var % Ticket' =
			
			DIVIDE(
			    [Ticket Medio] - [Ticket Médio Mês Anterior],
			    [Ticket Médio Mês Anterior]
			)
		displayFolder: Variações e Percentuais
		lineageTag: 6e59717d-a639-48ff-8d86-c12c182d644d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Botao HTML Visao Executiva' = ```
			
			"
			<style>
			    .card-btn {
			        width: 100%; height: 100%; padding: 12px 10px; border-radius: 20px; box-sizing: border-box;
			        background: linear-gradient(135deg, #2708A0 0%, #058ED9 100%); font-family: 'Segoe UI', sans-serif;
			        position: relative; overflow: hidden; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px;
			        box-shadow: 0 4px 10px rgba(0,0,0,0.15), inset 0 2px 5px rgba(255,255,255,0.25); 
			        transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
			    }
			    
			    /* Efeito intensificado: Aumenta, sobe 3px, sombra expande, brilho explode e cor fica viva */
			    .card-btn:hover {
			        transform: scale(1.03) translateY(-3px); 
			        box-shadow: 0 12px 24px rgba(0,0,0,0.35), inset 0 4px 15px rgba(255,255,255,0.6); 
			        filter: brightness(1.15) saturate(1.3); 
			    }
			</style>
			
			<div class='card-btn'>
			    <div style='position:absolute; top:-12px; right:-12px; width:60px; height:60px; border-radius:50%; background:rgba(255,255,255,.1);'></div>
			
			    <div style='width:40px; height:40px; border-radius:50%; background:#2708A0; display:flex; align-items:center; justify-content:center; box-shadow:0 2px 5px rgba(0,0,0,.25);'>
			        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='white' width='22' height='22'>
			            <path d='M19 6h-2c0-2.76-2.24-5-5-5S7 3.24 7 6H5c-1.1 0-1.99.9-1.99 2L3 20c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2zm-7-3c1.66 0 3 1.34 3 3H9c0-1.66 1.34-3 3-3zm0 10c-2.76 0-5-2.24-5-5h2c0 1.66 1.34 3 3 3s3-1.34 3-3h2c0 2.76-2.24 5-5 5z'/>
			        </svg>
			    </div>
			
			    <div style='display:flex; flex-direction:column; align-items:center; gap:2px;'>
			        <div style='font-size:13px; font-weight:700; color:#FFF; letter-spacing:.8px; text-align:center;'>
			            VISÃO EXECUTIVA
			        </div>
			        <div style='font-size:11px; color:#E2E8F0; font-weight:400; opacity:0.9;'>
			            Resumo Executivo
			        </div>
			    </div>
			</div>
			"
			```
		displayFolder: UI e Design
		lineageTag: 98712414-4041-49cc-90e5-76919935c8fe

	measure 'Botao HTML Visao Temporal' = ```
			
			"
			<style>
			    .card-btn {
			        width: 100%; height: 100%; padding: 12px 10px; border-radius: 20px; box-sizing: border-box;
			        background: linear-gradient(135deg, #2708A0 0%, #058ED9 100%); font-family: 'Segoe UI', sans-serif;
			        position: relative; overflow: hidden; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px;
			        box-shadow: 0 4px 10px rgba(0,0,0,0.15), inset 0 2px 5px rgba(255,255,255,0.25); 
			        transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
			    }
			    .card-btn:hover {
			        transform: scale(1.03) translateY(-3px); 
			        box-shadow: 0 12px 24px rgba(0,0,0,0.35), inset 0 4px 15px rgba(255,255,255,0.6); 
			        filter: brightness(1.15) saturate(1.3); 
			    }
			</style>
			
			<div class='card-btn'>
			    <div style='position:absolute; top:-12px; right:-12px; width:60px; height:60px; border-radius:50%; background:rgba(255,255,255,.1);'></div>
			    <div style='width:40px; height:40px; border-radius:50%; background:#2708A0; display:flex; align-items:center; justify-content:center; box-shadow:0 2px 5px rgba(0,0,0,.25);'>
			        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='white' width='22' height='22'>
			            <path d='M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11z'/>
			        </svg>
			    </div>
			    <div style='display:flex; flex-direction:column; align-items:center; gap:2px;'>
			        <div style='font-size:13px; font-weight:700; color:#FFF; letter-spacing:.8px; text-align:center;'>
			            VISÃO TEMPORAL
			        </div>
			        <div style='font-size:11px; color:#E2E8F0; font-weight:400; opacity:0.9;'>
			            Indicadores Estratégicos
			        </div>
			    </div>
			</div>
			"
			```
		displayFolder: UI e Design
		lineageTag: 94d6cfa0-fa04-4049-89e4-bd0ed76c546d

	measure 'Botao HTML Visao Operacional' = ```
			
			"
			<style>
			    .card-btn {
			        width: 100%; height: 100%; padding: 12px 10px; border-radius: 20px; box-sizing: border-box;
			        background: linear-gradient(135deg, #2708A0 0%, #058ED9 100%); font-family: 'Segoe UI', sans-serif;
			        position: relative; overflow: hidden; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px;
			        box-shadow: 0 4px 10px rgba(0,0,0,0.15), inset 0 2px 5px rgba(255,255,255,0.25); 
			        transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
			    }
			    .card-btn:hover {
			        transform: scale(1.03) translateY(-3px); 
			        box-shadow: 0 12px 24px rgba(0,0,0,0.35), inset 0 4px 15px rgba(255,255,255,0.6); 
			        filter: brightness(1.15) saturate(1.3); 
			    }
			</style>
			
			<div class='card-btn'>
			    <div style='position:absolute; top:-12px; right:-12px; width:60px; height:60px; border-radius:50%; background:rgba(255,255,255,.1);'></div>
			    <div style='width:40px; height:40px; border-radius:50%; background:#2708A0; display:flex; align-items:center; justify-content:center; box-shadow:0 2px 5px rgba(0,0,0,.25);'>
			        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='white' width='22' height='22'>
			            <path d='M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z'/>
			        </svg>
			    </div>
			    <div style='display:flex; flex-direction:column; align-items:center; gap:2px;'>
			        <div style='font-size:12px; font-weight:700; color:#FFF; letter-spacing:.8px; text-align:center; white-space:nowrap;'>
			            VISÃO OPERACIONAL
			        </div>
			        <div style='font-size:11px; color:#E2E8F0; font-weight:400; opacity:0.9;'>
			            Performance Comercial
			        </div>
			    </div>
			</div>
			"
			```
		displayFolder: UI e Design
		lineageTag: d8dcbfc7-89c0-466e-b325-6930feff8076

	measure 'Titulo HTML Capa' = ```
			
			"
			<div style='
			    width:100%;
			    height:100%;
			    display:flex;
			    flex-direction:column;
			    align-items:center;
			    justify-content:center;
			    font-family:Segoe UI, sans-serif;
			'>
			    <div style='
			        font-size: 56px;
			        font-weight: 800;
			        color: #2708A0;
			        letter-spacing: 1.5px;
			        text-shadow: 2px 4px 10px rgba(0,0,0,0.08);
			        text-align: center;
			        line-height: 1.1;
			        /* Efeito de Brilho Premium (Radial Gradient) */
			        background: radial-gradient(circle, rgba(255,255,255,0.85) 0%, rgba(255,255,255,0) 65%);
			        padding: 40px 120px;
			        margin-bottom: -32px; /* Compensa o padding para manter o subtítulo próximo */
			    '>
			        ANÁLISE COMERCIAL
			    </div>
			    
			    <div style='
			        font-size: 16px;
			        color: #058ED9;
			        font-weight: 600;
			        letter-spacing: 6px;
			        margin-top: 8px;
			        text-transform: uppercase;
			        position: relative;
			        z-index: 1; /* Garante que o subtítulo fique acima do brilho */
			    '>
			        Dashboard Gerencial
			    </div>
			    
			    <div style='
			        width: 100px;
			        height: 5px;
			        background: linear-gradient(90deg, #2708A0, #058ED9);
			        border-radius: 3px;
			        margin-top: 25px;
			    '></div>
			</div>
			"
			```
		displayFolder: UI e Design
		lineageTag: 7284265d-8f27-41cf-b8ce-6492500b9f14

	measure 'Texto HTML Assinatura' =
			
			"
			<div style='
			    width: 100%;
			    height: 100%;
			    font-family: Segoe UI, sans-serif;
			    display: flex;
			    align-items: center;
			    justify-content: center;
			'>
			    <div style='
			        font-size: 13px;
			        color: #6C7A89;
			        letter-spacing: 0.5px;
			    '>
			        Desenvolvido por <strong style='color: #2708A0;'>Felipe Tamiozzo</strong> &nbsp;<span style='color: #058ED9; font-weight: 900;'>|</span>&nbsp; <span style='color: #058ED9; font-weight: 600;'>Analista de Dados</span>
			    </div>
			</div>
			"
		displayFolder: UI e Design
		lineageTag: c22485ae-501c-4907-ac0f-81905ec588f5

	measure 'Botao HTML Instrucao Navegacao' = ```
			
			"
			<style>
			    .pulse-indicator {
			        display: inline-flex;
			        align-items: center;
			        justify-content: center;
			        padding: 10px 24px;
			        border-radius: 30px;
			        background: rgba(5, 142, 217, 0.08); /* Fundo azul bem suave e transparente */
			        border: 1px solid rgba(5, 142, 217, 0.3);
			        color: #2708A0; /* Texto no azul escuro do seu tema */
			        font-family: 'Segoe UI', sans-serif;
			        font-size: 13px;
			        font-weight: 600;
			        letter-spacing: 0.5px;
			        box-shadow: 0 4px 10px rgba(0,0,0,0.05);
			        animation: pulse 2s infinite;
			    }
			    
			    /* Efeito de pulsação suave ao redor do botão */
			    @keyframes pulse {
			        0% { box-shadow: 0 0 0 0 rgba(5, 142, 217, 0.4); }
			        70% { box-shadow: 0 0 0 10px rgba(5, 142, 217, 0); }
			        100% { box-shadow: 0 0 0 0 rgba(5, 142, 217, 0); }
			    }
			</style>
			
			<div style='width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;'>
			    <div class='pulse-indicator'>
			        
			        <!-- Ícone de Mão / Clique -->
			        <svg style='margin-right: 8px;' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='#058ED9' width='18' height='18'>
			            <path d='M9 11.24V7.5C9 6.12 10.12 5 11.5 5S14 6.12 14 7.5v3.74c1.21-.81 2-2.18 2-3.74C16 5.01 13.99 3 11.5 3S7 5.01 7 7.5c0 1.56.79 2.93 2 3.74zm9.84 4.63l-4.54-2.26c-.17-.07-.35-.11-.54-.11H13v-6c0-.83-.67-1.5-1.5-1.5S10 6.67 10 7.5v10.74l-3.43-.72c-.08-.01-.15-.03-.24-.03-.31 0-.59.13-.79.33l-.79.8 4.94 4.94c.27.27.65.44 1.04.44h6.79c.75 0 1.33-.55 1.44-1.28l.75-5.27c.01-.07.02-.14.02-.21 0-.62-.33-1.2-.85-1.47z'/>
			        </svg>
			        
			        Clique nos painéis acima para navegar
			        
			    </div>
			</div>
			"
			```
		displayFolder: UI e Design
		lineageTag: c24ad1d0-e0d0-4e44-a38e-048b0189303f

	measure 'Titulo HTML Insight Vendas' =
			
			"
			<div style='
			    width: 100%;
			    height: 100%;
			    display: flex;
			    flex-direction: column;
			    align-items: center;
			    justify-content: center;
			    font-family: Segoe UI, sans-serif;
			'>
			    <div style='
			        display: flex;
			        align-items: center;
			        justify-content: center;
			    '>
			        <!-- Ícone de Insight -->
			        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='#2708A0' width='26' height='26' style='margin-right: 8px; margin-bottom: 2px;'>
			            <path d='M16 6l2.29 2.29-4.88 4.88-4-4L2 16.59 3.41 18l6-6 4 4 6.3-6.29L22 12V6h-6z'/>
			        </svg>
			
			        <div style='
			            font-size: 28px;
			            font-weight: 800;
			            color: #2708A0;
			            letter-spacing: 0.5px;
			        '>
			            Insight de Vendas
			        </div>
			    </div>
			</div>
			"
		displayFolder: UI e Design
		lineageTag: 79ada707-4b05-44f1-9758-871d5d3b4d47

	measure 'Titulo HTML Analise Temporal' =
			
			"
			<div style='
			    width: 100%;
			    height: 100%;
			    display: flex;
			    flex-direction: column;
			    align-items: center;
			    justify-content: center;
			    font-family: Segoe UI, sans-serif;
			'>
			    <div style='
			        display: flex;
			        align-items: center;
			        justify-content: center;
			    '>
			        <!-- Ícone de Calendário/Tempo -->
			        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='#2708A0' width='26' height='26' style='margin-right: 8px; margin-bottom: 2px;'>
			            <path d='M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11z'/>
			        </svg>
			
			        <div style='
			            font-size: 28px;
			            font-weight: 800;
			            color: #2708A0;
			            letter-spacing: 0.5px;
			        '>
			            Análise Temporal
			        </div>
			    </div>
			</div>
			"
		displayFolder: UI e Design
		lineageTag: cbd0f7b0-bca0-4d75-8d2b-7d696a44bbfe

	measure 'Titulo HTML Visao Operacional' =
			
			"
			<div style='
			    width: 100%;
			    height: 100%;
			    display: flex;
			    flex-direction: column;
			    align-items: center;
			    justify-content: center;
			    font-family: Segoe UI, sans-serif;
			'>
			    <div style='
			        display: flex;
			        align-items: center;
			        justify-content: center;
			    '>
			        <!-- Ícone de Vendedor / Operacional -->
			        <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='#2708A0' width='26' height='26' style='margin-right: 8px; margin-bottom: 2px;'>
			            <path d='M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z'/>
			        </svg>
			
			        <div style='
			            font-size: 28px;
			            font-weight: 800;
			            color: #2708A0;
			            letter-spacing: 0.5px;
			        '>
			            Visão Operacional
			        </div>
			    </div>
			</div>
			"
		displayFolder: UI e Design
		lineageTag: 8165b03a-1c8b-4f4e-ab1a-e8951f230188

	partition _Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	changedProperty = Name

	annotation PBI_ResultType = Table

